In [1]:
import tensorflow as tf
import numpy as np

In [26]:
def weight_variable(shape):
    initial = tf.truncated_normal(shape, stddev=0.1)
    #initial = tf.ones(shape)
    return tf.Variable(initial)

def bias_variable(shape):
    initial = tf.constant(0.1, shape=shape)
    return tf.Variable(initial)

def conv2d(x, W):
    return tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding='SAME')

def max_pool_2x2(x):
    return tf.nn.max_pool(x, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME')

In [27]:
x_image = tf.ones(shape=[1,4,4,1])
W_conv1 = weight_variable([2, 2, 1, 1])
b_conv1 = bias_variable([1])

h_conv1 = conv2d(x_image, W_conv1) + b_conv1
h_conv1_relu = tf.nn.relu(h_conv1)
h_conv1_pool = max_pool_2x2(h_conv1_relu)

sess = tf.InteractiveSession()
tf.global_variables_initializer().run()
h_conv1_out = sess.run(h_conv1_pool)


In [28]:
print(h_conv1.shape)
print(h_conv1.eval())

(1, 4, 4, 1)
[[[[ 0.22609866]
   [ 0.22609866]
   [ 0.22609866]
   [ 0.16301668]]

  [[ 0.22609866]
   [ 0.22609866]
   [ 0.22609866]
   [ 0.16301668]]

  [[ 0.22609866]
   [ 0.22609866]
   [ 0.22609866]
   [ 0.16301668]]

  [[ 0.26623237]
   [ 0.26623237]
   [ 0.26623237]
   [ 0.17934561]]]]


In [29]:
print(W_conv1.eval())
print(W_conv1.eval().sum())

[[[[ 0.07934561]]

  [[ 0.08688677]]]


 [[[-0.01632893]]

  [[-0.02380479]]]]
0.126099


In [30]:
print(h_conv1_relu.eval())

[[[[ 0.22609866]
   [ 0.22609866]
   [ 0.22609866]
   [ 0.16301668]]

  [[ 0.22609866]
   [ 0.22609866]
   [ 0.22609866]
   [ 0.16301668]]

  [[ 0.22609866]
   [ 0.22609866]
   [ 0.22609866]
   [ 0.16301668]]

  [[ 0.26623237]
   [ 0.26623237]
   [ 0.26623237]
   [ 0.17934561]]]]


In [7]:
print(h_conv1_pool.eval())

[[[[ 0.        ]
   [ 0.06074855]]

  [[ 0.        ]
   [ 0.06074855]]]]
